// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    GyHeader: typeof import('./src/components/GyHeader.vue')['default']
    GyPage: typeof import('./src/components/GyPage.vue')['default']
    GyTable: typeof import('./src/components/GyTable.vue')['default']
    MapCon: typeof import('./src/components/MapCon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowCode: typeof import('./src/components/ShowCode.vue')['default']
    Siderbar: typeof import('./src/components/Siderbar.vue')['default']
    SjmapCon: typeof import('./src/components/SjmapCon.vue')['default']
  }
}
